### ISSUE TITLE
[Bug]: Not able to open on Windows Server 2022

### ISSUE THREAD

**Issue by 24khxn** [dankrusi/WindowsVirtualDesktopHelper#122]
### What happened?

Can't even open the software. Immediately pops up with the log info

### WVDH Version

1.15

### Windows Version

Windows Server 2022 (21H2)

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin10,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_23H2,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 20348
Windows Release: 2009
Windows Product: Windows Server 2022 Standard
Windows Version: 21H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin10

Log:
Using config file: C:\Users\shkhan\Downloads\WindowsVirtualDesktopHelper.Executable.v1.15\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 20348
GetImplementationForOS: Fallback to Windows 10 (fallback)
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
```

**Comment by dankrusi** [comment]
Hi, if you look at the README you will find Windows Server is not supported:
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/190233/06789640-a38b-4b99-bc15-13fed6df1b40)
