### ISSUE TITLE
[Bug]: Program crashes on startup

### ISSUE THREAD

**Issue by biconix** [dankrusi/WindowsVirtualDesktopHelper#124]
### What happened?

program crashes on startup started right after upgrade of winodws to latest insider build

### WVDH Version

1.15.0.0

### Windows Version

windows 11 build 23066

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_Insider,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_23H2,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 23606
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_Insider

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 23606
GetImplementationForOS: Detected Windows 11 Insider due to build >= 23403 
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by outsourcetoasia** [comment]
Confirmed, same problem here

**Comment by jarusaurus** [comment]
#127 and #129 related I think

**Comment by chmodseven** [comment]
Same here, seems to have been after a Windows overnight update just went through for Win 11 Home Version 23H2 (OS Build 22631.3085).

**Comment by dankrusi** [comment]
Thank you all for the bug reporting and help testing - please see the new official release v1.16: https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.16. This issue will be closed for now to avoid confusion - please open a new issue with your exact Windows version if you encounter problems.
