### ISSUE TITLE
[Bug]: no implementation loaded successfully

### ISSUE THREAD

**Issue by mcgwiz** [dankrusi/WindowsVirtualDesktopHelper#127]
### What happened?

Started the app. It immediately crashed.

### WVDH Version

1.15.0.0

### Windows Version

Windows 11 23H2 build 22635

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22635
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22635
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by SignalGroup** [comment]
Having the same issue.

**Comment by jarusaurus** [comment]
+1 with issue. Sorry for duplicate post #129 mark it as duplicate here. And link this there for additional info. 
Can remove that if its too confusing.

**Comment by dkfour** [comment]
+1 - just received this today after a windows update last night: 2024-01 Cumulative Update Preview for Windows 11 Version 22H2 for x64-based Systems (KB5034204)

**Comment by dmitry-gr** [comment]
The same update affected the Win 11 23H2 version too. The issue is solved by uninstalling this update.

**Comment by dankrusi** [comment]
Does this version work for you?
[WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14061700/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

**Comment by dankrusi** [comment]
Sorry what build revision? I.e. 22621.XXXX?

**Comment by dkfour** [comment]
> @dkfour Sorry what build revision? I.e. 22621.XXXX?

OS Name	Microsoft Windows 11 Enterprise
Version	10.0.22621 Build 22621
Hardware Abstraction Layer	Version = "10.0.22621.2506"

**Comment by dankrusi** [comment]
Thank you all for the bug reporting and help testing - please see the new official release v1.16: https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.16. This issue will be closed for now to avoid confusion - please open a new issue with your exact Windows version if you encounter problems.
