### ISSUE TITLE
[Bug]: loadimplementation fallback - win version issue?

### ISSUE THREAD

**Issue by jarusaurus** [dankrusi/WindowsVirtualDesktopHelper#129]
### What happened?

![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/80814501/57790b53-88c5-4716-9631-ae8e292491bb)
Got this error on system start. 
Not sure if its the win update that did it?
Thanks

### WVDH Version

v1.15

### Windows Version

Windows 11 version 23H2 OS build 26020.1000

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_23H2,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 26020
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_InsiderCanary

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 26020
GetImplementationForOS: Detected Windows 11 Insider Canary due to build >= 25314
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by Tarpal** [comment]
Just updated Windows and on startup immediately received a similar pop up message:

![VD-error](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/11710753/d284b696-7906-4288-a547-6c7c02675ab2)

**Comment by dankrusi** [comment]
Will see if we can get it working again ASAP...

**Comment by Trollwut** [comment]
same as the other two,

only got 1 Windows update today, which would be that one: `2024-01 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034204)`

Here is the error log of the app:

```
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by dankrusi** [comment]
Can everyone quickly confirm they are on Windows 11?

**Comment by chrisonline** [comment]
Yes I am on Windows 11.

**Comment by Tarpal** [comment]
![image](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/11710753/47e757f7-f795-4794-a01d-e309c0cd5f3a)

**Comment by Trollwut** [comment]
Indeed, the provided logs show Win10, but I am on Win11 like the others here.

**Comment by franciscoyira** [comment]
I have this problem too. It happened right after applying a Windows 11 cumulative update

Edition	Windows 11 Home
Version	23H2
Installed on	‎2022-‎10-‎15
OS build	22631.3085
Serial number	0F006YA213201J
Experience	Windows Feature Experience Pack 1000.22684.1000.0

**Comment by Trollwut** [comment]
Another software, which is being used to switch virtual desktop via hotkey, had a pull request to update some IDs.

Maybe this could be relevant?

https://github.com/Ciantic/VirtualDesktopAccessor/pull/87

**Comment by dankrusi** [comment]
@Trollwut perfect! exactly what I am looking for! Does this v16 work for you?
[WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14061691/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

**Comment by chrisonline** [comment]
> @Trollwut perfect! exactly what I am looking for! Does this v16 work for you? [WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14061691/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

I have tried it, but the same crash I think:
```
Oh no! It seems your version of Windows is not yet supported! This is most likely due to your Windows Version being a Insider/Canary build, or a having a new patch where the APIs have changed. You can report the issue, but please be patient as it's a lot of work to keep up with all the Windows versions! 
Error: No implementation loaded successfully, tried: VirtualDesktopWin11_23H2, VirtualDesktopWin11_Insider25314, VirtualDesktopWin11_Insider22631, VirtualDesktopWin11_Insider, VirtualDesktopWin11_22H2, VirtualDesktopWin11_21H2, VirtualDesktopWin10 (LoadImplementationWithFallback)
   bei WindowsVirtualDesktopHelper.App..ctor()
   bei WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.16.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider25314
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider25314...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider25314
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider22631
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider22631...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider22631
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by dankrusi** [comment]
@Trollwut  what is build revision? Ie. 22631.XXXX? Thanks, -dan

**Comment by chrisonline** [comment]
@dankrusi 22631.3085

**Comment by dankrusi** [comment]
@chrisonline This work? 
[WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14065324/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

**Comment by chrisonline** [comment]
@dankrusi Yes it works now! Great!!

**Comment by dankrusi** [comment]
@mcgwiz  @Trollwut @Tarpal let me know if this latest zip works for you - then I will publish the version...

**Comment by Digenie** [comment]
If I run this version (1.16) it works, but when I restart I get the same error as before.

**Comment by mcgwiz** [comment]
Works great for me, thank you.

**Comment by Trollwut** [comment]
> @Trollwut perfect! exactly what I am looking for! Does this v16 work for you? [WindowsVirtualDesktopHelper Executable v1.16.zip](https://github.com/dankrusi/WindowsVirtualDesktopHelper/files/14061691/WindowsVirtualDesktopHelper.Executable.v1.16.zip)

Hey there! Downloaded it and just run the exe file.

Still a crash:
 
![grafik](https://github.com/dankrusi/WindowsVirtualDesktopHelper/assets/3462975/e30af326-f2cf-40d0-8f23-0d15dc9fed5c)

```
Oh no! It seems your version of Windows is not yet supported! This is most likely due to your Windows Version being a Insider/Canary build, or a having a new patch where the APIs have changed. You can report the issue, but please be patient as it's a lot of work to keep up with all the Windows versions! 
Error: No implementation loaded successfully, tried: VirtualDesktopWin11_23H2, VirtualDesktopWin11_Insider25314, VirtualDesktopWin11_Insider22631, VirtualDesktopWin11_Insider, VirtualDesktopWin11_22H2, VirtualDesktopWin11_21H2, VirtualDesktopWin10 (LoadImplementationWithFallback)
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.16.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Users\troll\Downloads\WindowsVirtualDesktopHelper.Executable.v1.16\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider25314
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider25314...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider25314
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider22631
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider22631...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider22631
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10
```

**Comment by Trollwut** [comment]
Forget what I said. I thought both "new version" are the same.

Downlaoded the latter one and this one works for me as well :)

**Comment by Khaos66** [comment]
Is this fix making it into an official release soon ?

**Comment by dankrusi** [comment]
Thank you all for the bug reporting and help testing - please see the new official release v1.16: https://github.com/dankrusi/WindowsVirtualDesktopHelper/releases/tag/v1.16. This issue will be closed for now to avoid confusion - please open a new issue with your exact Windows version if you encounter problems.
