### ISSUE TITLE
[Bug]: LoadImplementationWithFallback: no implementation loaded successfully

### ISSUE THREAD

**Issue by ImTrikk** [dankrusi/WindowsVirtualDesktopHelper#140]
### What happened?

This is what is saying everytime I start up my laptop;

LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Release: 2009
Windows Product: Windows 10 Home Single Language
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...

### WVDH Version

1.15.0.0

### Windows Version

Windows 11 Home Single Language 23H2 OS BUILD 22631.3155

### Relevant log output

```shell
LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_23H2,VirtualDesktopWin11_InsiderCanary,VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 22631
Windows Release: 2009
Windows Product: Windows 10 Home Single Language
Windows Version: 23H2
Windows Virtual Desktop Helper Version: 1.15.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_23H2

Log:
Using config file: C:\Program Files (x86)\Windows Virtual Desktop Helper\WindowsVirtualDesktopHelper.exe.config
GetImplementationForOS: Windows Build Version: 22631
GetImplementationForOS: Detected Windows 11 23H2 due to build >= 22621.2050
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_23H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_InsiderCanary
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_InsiderCanary...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_InsiderCanary
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
```

**Comment by ericreeves** [comment]
Duplicate of #139
