### ISSUE TITLE
[Bug]: 24H2 Modification of configuration file not accepted

### ISSUE THREAD

**Issue by AndroSteph** [dankrusi/WindowsVirtualDesktopHelper#160]
### What happened?

I'd like to put the office number, which is currently in black, in white. If I change the “#general.theme: ‘auto’ parameter to either ‘black’ or ‘white’. And even any other change in this file is restored when I quit and relaunch “Windows Virtual Desktop Helper”. The file I'm modifying is in “%appdata%\WindowsVirtualDesktopHelper”.

Am I doing something wrong or is this a bug?

Thanks for this software, it works almost completely under 24H2, but not 100%.

It doesn't launch at startup if I've checked the right box (in “settings”). However, I can launch it by putting it manually in the “Start” menu ;-)

Thank you for your advice, I remain at your disposal if necessary and I apologize for my bad English.

### WVDH Version

VirtualDesktopWin11_23H2_2921

### Windows Version

Windows 11 24H2

### Relevant log output

```shell
Using config file(s):

   C:\Users\XXXXXXX\AppData\Roaming\WindowsVirtualDesktopHelper\WindowsVirtualDesktopHelper.exe.config
Config: 

   feature.showDesktopSwitchOverlay: false

   feature.showPrevNextIcons: false

   general.startupWithWindows: false
GetImplementationForOS: Windows Build Version: 26100.2161
GetImplementationForOS: Detected Windows 11 Insider Canary 25314 due to build >= 25314
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider25314
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider25314...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider25314: System.Exception: LoadImplementation: could not load VirtualDesktop API implementation VirtualDesktopWin11_Insider25314: The type initializer for 'DesktopManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider25314.IServiceProvider10.QueryService(Guid& service, Guid& riid)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider25314.DesktopManager..cctor()

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider25314.Current()

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementationWithFallback(String name)
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider22631
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider22631...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider22631: System.Exception: LoadImplementation: could not load VirtualDesktop API implementation VirtualDesktopWin11_Insider22631: The type initializer for 'DesktopManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DesktopManager' threw an exception. ---> System.NotImplementedException: The method or operation is not implemented.

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider22631.IServiceProvider10.QueryService(Guid& service, Guid& riid)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider22631.DesktopManager..cctor()

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider22631.Current()

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementationWithFallback(String name)
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider: System.Exception: LoadImplementation: could not load VirtualDesktop API implementation VirtualDesktopWin11_Insider: The type initializer for 'DesktopManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'DesktopManager' threw an exception. ---> System.InvalidCastException: Specified cast is not valid.

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider.IServiceProvider10.QueryService(Guid& service, Guid& riid)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider.DesktopManager..cctor()

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Implementation.VirtualDesktopWin11_Insider.Current()

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   --- End of inner exception stack trace ---

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementation(String name)

   at WindowsVirtualDesktopHelper.VirtualDesktopAPI.Loader.LoadImplementationWithFallback(String name)
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_23H2_2921
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_23H2_2921...
LoadImplementationWithFallback: success!
```

**Comment by AndroSteph** [comment]
In fact, it's me who doesn't know how. I thought I could change the color (currently black) of the office number visible in the taskbar (bottom right). As I understand it, that's not possible.

I've also tried using keystrokes such as “Ctrl + Win + NumPad1” to go directly to the “no 1” desktop, but to no avail.

**Comment by dankrusi** [comment]
Lines in the config starting with # are for comments. Remove the # to make the config active and persistent.

**Comment by AndroSteph** [comment]
Thank you very much ! ;-)
