### ISSUE TITLE
Error: LoadImplementationWithFallback: no implementation loaded successfully

### ISSUE THREAD

**Issue by kegobass** [dankrusi/WindowsVirtualDesktopHelper#39]
Issue launching WindowsVirtualDesktopHelper on latest Windows 11 Insider (Dev channel).

LoadImplementationWithFallback: no implementation loaded successfully, tried: VirtualDesktopWin11_Insider,VirtualDesktopWin11_22H2,VirtualDesktopWin11_21H2,VirtualDesktopWin10
   at WindowsVirtualDesktopHelper.App..ctor()
   at WindowsVirtualDesktopHelper.Program.Main(String[] args)

Windows Build: 23506
Windows Release: 2009
Windows Product: Windows 10 Pro
Windows Version: 22H2
Windows Virtual Desktop Helper Version: 1.11.0.0
Virtual Desktop Implementation: VirtualDesktopWin11_Insider

Log:
GetImplementationForOS: Windows Build Version: 23506
GetImplementationForOS: Detected Windows 11 Insider due to build >= 23403 
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_Insider
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_Insider...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_Insider
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_22H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_22H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_22H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin11_21H2
LoadImplementation: Loading VDImplementation: VirtualDesktopWin11_21H2...
LoadImplementationWithFallback: failed to load VirtualDesktopWin11_21H2
LoadImplementationWithFallback: trying to load implementation VirtualDesktopWin10
LoadImplementation: Loading VDImplementation: VirtualDesktopWin10...
LoadImplementationWithFallback: failed to load VirtualDesktopWin10

**Comment by kegobass** [comment]
Duplicate
